export enum screenNames {
  GET_STARTED = "GET_STARTED",
  LOGIN = "LOGIN",
  HOME = "HOME",
  HISTORY = "HISTORY",
  AI_CHAT = "AI-CHAT",
  SETTINGS = "SETTINGS",
  VOICE_CHATTING = "VOICE_CHATTING",
  TEXT_CHATTING = "TEXT_CHATTING",
  BOTTOM_TAB = "BOTTOM_TAB",
}
