export enum screenNames {
  GET_STARTED = "GET-STARTED",
  LOGIN = "LOGIN",
  HOME = "HOME",
  HISTORY = "HISTORY",
  AI_CHAT = "AI-CHAT",
  SETTINGS = "SETTINGS",
  VOICE_CHATTING = "VOICE-CHATTING",
  TEXT_CHATTING = "TEXT-CHATTING",
  BOTTOM_TAB = "BOTTOM-TAB",
  ABOUT_US = "ABOUT-US",
  TERMS_OF_USE = "TERMS-OF-USE",
}
