import Animated, {
  FadeIn,
  FadeOut,
  ZoomIn,
  ZoomOut,
  SlideInUp,
  SlideOutUp,
  SlideInDown,
  SlideOutDown,
  SlideInLeft,
  SlideOutLeft,
  SlideInRight,
  SlideOutRight,
  BounceIn,
  BounceOut,
  BounceInLeft,
  BounceOutLeft,
  BounceInRight,
  BounceOutRight,
  BounceInDown,
  BounceOutDown,
  BounceInUp,
  BounceOutUp,
} from "react-native-reanimated";

export const animationIn = {
  ZoomIn,
  SlideInUp,
  SlideInDown,
  SlideInLeft,
  SlideInRight,
  BounceIn,
  BounceInLeft,
  BounceInRight,
  BounceInDown,
  BounceInUp,
  FadeIn,
};

export const animationOut = {
  ZoomOut,
  SlideOutUp,
  SlideOutDown,
  SlideOutLeft,
  SlideOutRight,
  BounceOut,
  BounceOutLeft,
  BounceOutRight,
  BounceOutDown,
  BounceOutUp,
  FadeOut,
};
